### ISSUE TITLE
[Bug]: Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by ghost** [iconomy5legacy/iConomy#23]
The following error occurs on a new install of MySQL. There is no configuration option that sets SSL to true, as the `useSSL` is set to false in the code. I've tried the alternative fix we found a few months back but it does not work for some reason anymore and this should probably get fixed.

```
[01:43:10 INFO]: [iConomy] [iConomy] Could not create connection: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
[01:43:10 ERROR]: [iConomy] Database initialization failed: java.lang.NullPointerException: Cannot invoke "java.sql.Connection.getMetaData()" because "conn" is null
```

As a request, could we potentially get editable flags instead of a useSSL option?

**Comment by LlmDl** [comment]
It would appear the default config never had the UseSSL option added to it. You can add it to the config like so:
```
          MySQL:
              Username: 'root'
              Password: 'pass'
              Hostname: 'localhost'
              Port: 3306
              UseSSL: true
```
or regenerate a new config using this build: https://cdn.discordapp.com/attachments/669247087329673228/890553529813577778/iConomy-5.14.jar

Let me know if either of those work on the new MySQL, otherwise it might be time to fix up some iconomy.

**Comment by LlmDl** [comment]
Use this version instead: 
https://cdn.discordapp.com/attachments/669247087329673228/890558460209549332/iConomy-5.14.jar

Let it make a new config, a flags line will appear.
